# Generated by Django 2.0.7 on 2019-12-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userintegral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/img_avatar/default.jpg', upload_to='img_avatar/'),
        ),
    ]
