# Generated by Django 2.0.7 on 2019-12-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.IntegerField(choices=[(1, '进货'), (0, '退货')])),
                ('count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
            options={
                'db_table': 'InventoryChange',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony_name', models.CharField(max_length=256)),
                ('addr', models.CharField(max_length=256)),
                ('linkman', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Supplier2Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('supplier', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='adminer.Supplier')),
            ],
            options={
                'db_table': 'Supplier2Product',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(through='adminer.Supplier2Product', to='product.Product'),
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='supplier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='adminer.Supplier'),
        ),
    ]
