# Generated by Django 2.0.7 on 2019-12-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('adminer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_num', models.IntegerField(default=0)),
                ('current_invintory', models.IntegerField(default=0)),
                ('sale_num', models.IntegerField(default=0)),
                ('product', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
