# Generated by Django 2.0.7 on 2019-12-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('describe', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('img', models.ImageField(upload_to='media/img_prod/')),
                ('is_unshelve', models.BooleanField(default=0)),
                ('repertory', models.IntegerField()),
                ('sale_num', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
