# Generated by Django 2.0.7 on 2019-12-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191217_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
